### ISSUE TITLE
Close All option in Code Tabs does not warn about unsaved work

### ISSUE THREAD

**Issue by GabeContra** [qorf/quorum-studio#2]
The context menu for the **Code Tabs** has the option for **Close All** or **Close Other** but neither option warns that the tabs being closed have unsaved work. Since there is no way to tell if a tab has unsaved work at the moment there should probably at least be a warning like when closing Quorum Studio with unsaved work.

**Comment by andreas-stefik** [comment]
This is fixed in Quorum Studio 4.0.
